/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import LogicaReporteIngresos.ReporteFila;
import LogicaReporteIngresos.ReporteGrafico;
import LogicaReporteIngresos.ReporteLogica;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author USER
 */
public class Reporte extends javax.swing.JPanel {
    DefaultTableModel modelo;
    ReporteLogica logica = new ReporteLogica();
    ReporteGrafico controlGraficos = new ReporteGrafico();
    
    public Reporte() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(1100,550));
        modelo = (DefaultTableModel)tbl_Reporte.getModel();
        jdc_De.setDateFormatString("dd/MM/yyyy");
        jdc_Hasta.setDateFormatString("dd/MM/yyyy");
        
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_Buscar = new javax.swing.JButton();
        jdc_De = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jdc_Hasta = new com.toedter.calendar.JDateChooser();
        btn_Refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Reporte = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_CantidadPrestamos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_DineroGanado = new javax.swing.JLabel();
        btn_Graficar = new javax.swing.JButton();
        btn_Graficar2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reporte de Ingresos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 290, 50));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Intervalo");

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/search (3).png"))); // NOI18N
        btn_Buscar.addActionListener(this::btn_BuscarActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("De:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hasta:");

        btn_Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Refresh (1).png"))); // NOI18N
        btn_Refresh.addActionListener(this::btn_RefreshActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdc_De, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jdc_Hasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdc_De, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jdc_Hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 190));

        tbl_Reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prestamo", "Id Ejemplar", "Fecha Prestamo", "Fecha Devolucion", "Usuario", "Libro", "Costo", "Dias de retraso", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Reporte);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 900, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Resumen");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad de Prestamos:");

        lbl_CantidadPrestamos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_CantidadPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CantidadPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CantidadPrestamos.setText("###");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dinero Ganado:");

        lbl_DineroGanado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_DineroGanado.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DineroGanado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_DineroGanado.setText("S/ ###");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_CantidadPrestamos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 13, Short.MAX_VALUE))
                            .addComponent(lbl_DineroGanado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lbl_CantidadPrestamos)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(lbl_DineroGanado)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, 210));

        btn_Graficar.setText("Graficar");
        btn_Graficar.addActionListener(this::btn_GraficarActionPerformed);
        jPanel2.add(btn_Graficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        btn_Graficar2.setText("Graficar 2");
        btn_Graficar2.addActionListener(this::btn_Graficar2ActionPerformed);
        jPanel2.add(btn_Graficar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 590));
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarResumen () {
        //Cantidad de filas actuales
        int totalPrestamos = tbl_Reporte.getRowCount();
        lbl_CantidadPrestamos.setText(String.valueOf(totalPrestamos));
        
        //Suma de todos los valores de la columna total
        double sumaDinero = 0.0;
        for (int i = 0; i < totalPrestamos; i++) {
            try {
                Object valorCelda = tbl_Reporte.getValueAt(i, 8);
                if (valorCelda != null) {
                    double totalFila = Double.parseDouble(valorCelda.toString());
                    sumaDinero += totalFila;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            }
        }
        lbl_DineroGanado.setText(String.format("S/ %.2f", sumaDinero));
    }
    
    
    
     public void mostrarTabla () {
         modelo.setRowCount(0);
         //traer la lista de objetos
         ArrayList<ReporteFila> listaFilas = logica.obtenerHistorialGeneral();
         
         for (ReporteFila r : listaFilas) {
             Object [] fila = new Object[9];
             fila [0] = r.getIdPrestamo();
             fila [1] = r.getIdejemplar();
             fila [2] = r.getFechaPrestamo();
             fila [3] = r.getFechaDevolucion();
             fila [4] = r.getUsuario();
             fila [5] = r.getLibro();
             fila [6] = r.getCosto();
             fila [7] = r.getDiasRetraso();
             fila [8] = r.getTotal();
             modelo.addRow(fila);
         }
         actualizarResumen();
     }
     
     public void FiltrarTablaPorFecha (java.util.Date de, java.util.Date hasta) {
         modelo.setRowCount(0);
         //traer la lista de objetos
         ArrayList<ReporteFila> listaFilas = logica.obtenerHistorialFiltrado(de, hasta);
         
         for (ReporteFila r : listaFilas) {
             Object [] fila = new Object[9];
             fila [0] = r.getIdPrestamo();
             fila [1] = r.getIdejemplar();
             fila [2] = r.getFechaPrestamo();
             fila [3] = r.getFechaDevolucion();
             fila [4] = r.getUsuario();
             fila [5] = r.getLibro();
             fila [6] = r.getCosto();
             fila [7] = r.getDiasRetraso();
             fila [8] = r.getTotal();
             modelo.addRow(fila);
         }
         actualizarResumen();
     }
    
    private void btn_GraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GraficarActionPerformed
        if (tbl_Reporte.getRowCount() == 0 ) {
            JOptionPane.showMessageDialog(this, "No hay datos en la tabla para graficar.");
            return;
        }
        // pedimos a la clase fabrique el panel grafico
        ChartPanel panelGrafico = controlGraficos.obtenerGraficoBarras(modelo);
        
        // Ventana Flotante
        JFrame ventana = new JFrame("Estadísticas - Gráfico de Barras");
        ventana.setContentPane(panelGrafico);
        ventana.setSize(800, 500);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_GraficarActionPerformed

    private void btn_Graficar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Graficar2ActionPerformed
        if (tbl_Reporte.getRowCount() == 0) {
           JOptionPane.showMessageDialog(this, "No hay datos en la tabla para graficar.");
           return;
        }
        
        // pedimos a la clase fabrique el panel grafico
        ChartPanel panelGrafico = controlGraficos.obtenerGraficoPie(modelo);
        
        // Ventana Flotante
        JFrame ventana = new JFrame("Estadísticas - Gráfico de Pastel");
        ventana.setContentPane(panelGrafico);
        ventana.setSize(600, 500);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_Graficar2ActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        java.util.Date FechaInicio = jdc_De.getDate();
        java.util.Date FechaFin = jdc_Hasta.getDate();
        // Validacion 
        if (FechaInicio == null || FechaFin == null) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione ambas fechas para buscar");
            return;
        }
        // Validacion de rango
        if (FechaInicio.after(FechaFin)) {
            JOptionPane.showMessageDialog(this, "La fecha 'De' no puede ser posterior a la fecha 'Hasta'.");
            return;
        }
        FiltrarTablaPorFecha(FechaInicio, FechaFin);
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshActionPerformed
        jdc_De.setDate(null);
        jdc_Hasta.setDate(null);
        
        mostrarTabla();
    }//GEN-LAST:event_btn_RefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Graficar;
    private javax.swing.JButton btn_Graficar2;
    private javax.swing.JButton btn_Refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdc_De;
    private com.toedter.calendar.JDateChooser jdc_Hasta;
    private javax.swing.JLabel lbl_CantidadPrestamos;
    private javax.swing.JLabel lbl_DineroGanado;
    private javax.swing.JTable tbl_Reporte;
    // End of variables declaration//GEN-END:variables
}
